### ISSUE TITLE
SPT 3.10

### ISSUE THREAD

**Issue by StressOzz** [Likroll/yakyem#1]
Please make [yakyem](https://github.com/Likroll/yakyem) for SPT 3.10 :)

**Comment by Likroll** [comment]
Unfortunately, due to the Thanksgiving holiday, I won't be able to work on it today, but I'll see what I can do tomorrow. I haven't played SPT in a while, so I'm not sure what has and hasn't changed.

**Comment by Likroll** [comment]
To give an update, I got sick so there's going to be a delay, but having looked a little, it doesn't seem like updating will be too hard. At worst, expect an update by the end of week.

**Comment by Likroll** [comment]
I created a new release here and uploaded it to the mod page. If you run into any issues, feel free to let me know.
